<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Polly" Version="8.6.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Postgres\Infrastructure.Postgres.csproj" />
  </ItemGroup>

</Project>
